### ISSUE TITLE
sbt test fails with `Error: Cannot find module './scalajs.webpack.config'`

### ISSUE THREAD

**Issue by LLCampos** [AlexITC/chrome-scalajs-template#21]
If I clone the project and run `sbt test` I get:

```
[info] Fast optimizing /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/chrome-scalajs-template-test-fastopt
[info] Writing and bundling the test loader
[error] /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js:74
[error] 				throw err;
[error] 				^
[error] Error: Cannot find module './scalajs.webpack.config'
[error] Require stack:
[error] - /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/dev.webpack.config.js
[error] - /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js
[error] - /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js
[error] - /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/bin/webpack.js
[error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[error]     at Module.require (internal/modules/cjs/loader.js:887:19)
[error]     at require (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[error]     at Object.<anonymous> (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/dev.webpack.config.js:3:18)
[error]     at Module._compile (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[error]     at Module.load (internal/modules/cjs/loader.js:863:32)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[error]     at Module.require (internal/modules/cjs/loader.js:887:19)
[error]     at require (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[error]     at WEBPACK_OPTIONS (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js:115:13)
[error]     at requireConfig (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js:117:6)
[error]     at /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js:124:17
[error]     at Array.forEach (<anonymous>)
[error]     at module.exports (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js:122:15)
[error]     at /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js:71:45
[error]     at Object.parse (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/yargs/yargs.js:567:18)
[error]     at /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js:49:8
[error]     at Object.<anonymous> (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js:375:3)
[error]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[error]     at Module.load (internal/modules/cjs/loader.js:863:32)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[error]     at Module.require (internal/modules/cjs/loader.js:887:19)
[error]     at require (internal/modules/cjs/helpers.js:74:18)
[error]     at Object.<anonymous> (/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/bin/webpack.js:80:2)
[error]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[error]     at Module.load (internal/modules/cjs/loader.js:863:32) {
[error]   code: 'MODULE_NOT_FOUND',
[error]   requireStack: [
[error]     '/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/dev.webpack.config.js',
[error]     '/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/utils/convert-argv.js',
[error]     '/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack-cli/bin/cli.js',
[error] Failure on parsing the output of webpack: No content to map due to end-of-input
[error]     '/home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/bin/webpack.js'
[error]  at [Source: (ProcessPipeInputStream); line: 1, column: 0]
[error]   ]
[error] }
[error] You can try to manually execute the command
[error] node /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/bin/webpack --bail --profile --json --mode development --config /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/dev.webpack.config.js /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/chrome-scalajs-template-test-fastopt-loader.js --output /home/lcampos/Development/chrome-scalajs-template/target/scala-2.13/scalajs-bundler/test/chrome-scalajs-template-test-fastopt-bundle.js
[error] 
[error] stack trace is suppressed; run last Test / jsEnvInput for the full output
[error] (Test / jsEnvInput) Non-zero exit code: 1
[error] Total time: 202 s (03:22), completed 21/02/2021, 08:36:02
```

**Comment by LLCampos** [comment]
Removing the `webpackConfigFile := ` statement from `build.sbt` seems to "solve it". Although not helpful if you need custom configs. :(

**Comment by AlexITC** [comment]
I have a private project that has some tests, I will try to backport such config here, and setup a CI to avoid the issue.

Thanks!

**Comment by AlexITC** [comment]
I have finally integrated circleci, and pushed a workaround to run tests with a custom webpack config, i hope it helps.
